---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
  - name: zebedee

outputs:
  - name: zebedee-cms
  - name: zebedee-reader

run:
  path: zebedee/ci/scripts/build.sh
